### PR TITLE
modifying the validation of input-field.

### PR DESCRIPTION
**Pull request by lakshmiprasannakusumanchi**
I have modified the name-input validation i.e., only alphabets are allowed .
fix issue #207
image

### CODE REVIEW

**Comment by lakshmiprasannakusumanchi** [comment]
@Abhirup-02 is there any problem??

**Comment by zeitgeistxx** [comment]
No it's perfectly fine.

But make relevant branches to work on issues then make PR

**Comment by lakshmiprasannakusumanchi** [comment]
> No it's perfectly fine.
> 
> But make relevant branches to work on issues then make PR

I didn't understand could you please explain.

**Comment by zeitgeistxx** [comment]
Suppose you are working on name validation. Make a relevant branch like name-validation from base branch and work there.


So, when merge conflict arises, for me it becomes easy to resolve

**Pull request closed without merging**
