### PR TITLE
Changed navbar component

### PR DESCRIPTION
**Pull request by Abhinavcode13**
Hello @Abhirup-02 for now I have resolved the issue of logo which i told you earlier and the and style of li in the navbar.

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
Just review this PR @Abhirup-02

**Comment by zeitgeistxx** [comment]
@Abhinavcode13 i have fixed it already, And those dots before navbar items look bad.

**Comment by Abhinavcode13** [comment]
Any hint how to work on the animation part of it , tried all possible ways 😄 @Abhirup-02

**Comment by zeitgeistxx** [comment]
@Abhinavcode13 I have to try then

**Comment by Abhinavcode13** [comment]
@Abhirup-02 hmmm 👁️ god mode lol

**Comment by zeitgeistxx** [comment]
Nah nah DAA exam today @Abhinavcode13

**Comment by Abhinavcode13** [comment]
ohh All the best buddy @Abhirup-02

**Pull request closed without merging**
