### PR TITLE
Table of Contents added to README

### LINKED ISSUE #7: Rewriting Readme.md
The Readme file is incomplete.
**Can I make a new** readme to be shown with all the details?
(For GSSOC23)

### PR DESCRIPTION
**Pull request by Atharva-3000**
Successfully added the Table of Contents to the README,
this closes #7  
Here's the screenshot

screenshotreadme

### CODE REVIEW

**Comment by Atharva-3000** [comment]
@Abhirup-02 can you check this PR once, I can do updates if you want any changes.
Thanks : )

**Comment by zeitgeistxx** [comment]
As of now it seems okay, If anything  I want to change later i will let you know

**Review by zeitgeistxx — APPROVED** [review]
It's fine

**Comment by Atharva-3000** [comment]
Hey @Abhirup-02, can you add relevant tags to this PR regarding GSSOC23, or is fine?

**Comment by zeitgeistxx** [comment]
@Atharva-3000 your PR holds the issue no, so I think its fine. But still let me ask project managers

**Comment by Atharva-3000** [comment]
> @Atharva-3000 your PR holds the issue no, so I think its fine. But still let me ask project managers

Sure 👍

**Comment by Atharva-3000** [comment]
> @Atharva-3000 your PR holds the issue, no, so I think its fine. But still, let me ask project managers

Any updates on the labels?

**Pull request merged**
