### PR TITLE
added animation effects in front page

### PR DESCRIPTION
**Pull request by Illaf**
I have created animation effects in front page of website. Please review them

### CODE REVIEW

**Review by zeitgeistxx — APPROVED** [review]

**Review by zeitgeistxx — CHANGES_REQUESTED** [review]
@Illaf  aos only applied for the first section. What about the other sections?

**Comment by zeitgeistxx** [comment]
@Illaf  keep .env.example as it was. Why did you delete it

**Comment by Illaf** [comment]
@Abhirup-02 I mentioned for applying effects in the front page but since you want I will apply effects to the rest of the parts as well.
Sorry for the env file. I will delete .env.local file and restore .env.example file

**Comment by zeitgeistxx** [comment]
@Illaf there's no problem with .env.local. it's ignored.  
.env.example is there for people to know the names of env variables

**Comment by zeitgeistxx** [comment]
@Illaf one more thing i am having conflicts in package-lock.json. Can you delete your node_modules and package-lock then npm install the packages again. It might fix the conflict.

**Comment by Illaf** [comment]
> @Illaf there's no problem with .env.local. it's ignored. .env.example is there for people to know the names of env variables

That means I don't need to remove .env.local right?

**Comment by Illaf** [comment]
> @Illaf one more thing i am having conflicts in package-lock.json. Can you delete your node_modules and package-lock then npm install the packages again. It might fix the conflict.

@Abhirup-02 Sure👍

**Comment by zeitgeistxx** [comment]
> > @Illaf there's no problem with .env.local. it's ignored. .env.example is there for people to know the names of env variables
> 
> That means I don't need to remove .env.local right?

yeah, that won't effect. It is only stored in your machine locally.

**Pull request closed without merging**
