### PR TITLE
close button added in menu fixed #25

### LINKED ISSUE #25: need a close button in responsive navbar
When we click on the menu button, the menu opens, and there is also a close button available there.

Screenshot (96)

### PR DESCRIPTION
**Pull request by mandliyarajendra11**
okay so before that when we click on the menu button, the menu opens, and there is no  close button available there.

but now  issue fixed #25

### CODE REVIEW

**Review by zeitgeistxx — APPROVED** [review]
Working just fine. Thanks.

**Comment by zeitgeistxx** [comment]
@mandliyarajendra11 I just reviewed you PR, the close button looks so small. Make its size same as the menu button.

**Comment by zeitgeistxx** [comment]
Make another PR then.

**Comment by mandliyarajendra11** [comment]
@Abhirup-02  okay

**Pull request closed without merging**
