### PR TITLE
Footer redesign and responsiveness

### PR DESCRIPTION
**Pull request by karthiknadar1204**
Refer issue #13 , continuation for the same issue with a responsive layout
Screenshot 2023-05-31 at 12 19 43 PM

@Abhirup-02

### CODE REVIEW

**Review by zeitgeistxx — APPROVED** [review]

**Comment by zeitgeistxx** [comment]
@karthiknadar1204 it's looking like this
Screenshot_20230531_061443

**Comment by karthiknadar1204** [comment]
It looked fine in my system,will check it in a bit and revert back, responsiveness is fine?

**Comment by zeitgeistxx** [comment]
> It looked fine in my system,will check it in a bit and revert back, responsiveness is fine?

Haven't checked it

**Comment by karthiknadar1204** [comment]
@Abhirup-02 Checking and will share review

**Comment by karthiknadar1204** [comment]
Screenshot 2023-05-31 at 10 24 07 PM

@Abhirup-02 Looks perfect on my screen

**Comment by zeitgeistxx** [comment]
@karthiknadar1204  your screen width is different

**Comment by zeitgeistxx** [comment]
And there's no min width to it, so horizontal scrollbar is appearing, Check the vercel preview

**Comment by Abhirup-02** [comment]
Check the vercel preview

**Comment by karthiknadar1204** [comment]
Will tweak the code and share it again

**Comment by karthiknadar1204** [comment]
@Abhirup-02 Please share your screen width, will render the components accordingly and will also set a max width, lets wrap up this issue once and for all

**Pull request closed without merging**
