### PR TITLE
Made changes in footer section

### PR DESCRIPTION
**Pull request by Riyazul555**
Screenshot (318)

### CODE REVIEW

**Comment by Riyazul555** [comment]
@Abhirup-02 please review this pR

**Comment by Riyazul555** [comment]
I have also fixed the Sign in text improvement for the issue #264

**Comment by Riyazul555** [comment]
@Abhirup-02 take your time and review the pR........Thanks

**Review by zeitgeistxx — APPROVED** [review]

**Comment by Riyazul555** [comment]
@Abhirup-02 please merge this pR if you have approved these changes and everything seems right ...... Thanks

**Comment by Riyazul555** [comment]
@Abhirup-02 if you have approved these changes please merge this pR........Thanks

**Comment by zeitgeistxx** [comment]
@Riyazul555  it is not responsive. Fix that 

Screenshot 2023-06-30 063636

Screenshot 2023-06-30 063707

**Pull request closed without merging**
