### PR TITLE
Suggested Style Changed

### LINKED ISSUE #160: [STYLE CHANGE] Stats
**Description:**

[Provide a clear and concise description of the style change you are requesting.]

Above Contact us page there are cards with numbers and we can add design so that it could change dynamically from zero to that particular number. Like 1000 will be shown as 0 to 1000 for particular time where numbers will be added

**Reason for Change:**

[Explain the reasons behind the requested style change, such as usability, branding, or user experience.]

Most of user friendly website has this feature which attracts users. It is better and user friendly 

**Current Styling:**

[Describe the current styling that needs to be changed.]

Current Design is just card with some numbers which does not look good.

**Proposed Styling:**

[Describe the desired styling or changes you would like to see.]

Can Change it to dynamic numbering which is user friendly

**Screenshots or Design Mockups (optional):**

[If available, include relevant screenshots or design mockups illustrating the requested style changes.]

Screenshot from 2023-06-03 16-28-17

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [ ] Low
- [ ] Medium
- [x] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

### PR DESCRIPTION
**Pull request by Harshu467**
Change it to dynamic numbering which is user friendly.

Fixes #160

### CODE REVIEW

**Comment by Harshu467** [comment]
@Abhirup-02 Please Take a look , I have implemented , it looks more cool

**Review by zeitgeistxx — APPROVED** [review]

**Comment by zeitgeistxx** [comment]
@Harshu467  There's a 6s delay in starting of that animation.

But I don't want it that way. Look at your issue I suggested something there.

**Comment by Harshu467** [comment]
@Abhirup-02 How Many second delay do you want then?

**Comment by zeitgeistxx** [comment]
Delay shouldn't be static.....when the user reaches the location only then start the animation.So it has to dynamic

**Comment by Harshu467** [comment]
@Abhirup-02 , I have updated please check I have created PR , checked it and merge it

**Review by zeitgeistxx — APPROVED** [review]

**Comment by zeitgeistxx** [comment]
It works just perfect.

**Pull request merged**
