### PR TITLE
New Scrollbar Gssoc'23

### LINKED ISSUE #19: Making a new scroll-bar [GSSOC'23]
Changing the scrollbar as per the UI to give a smooth effect to it.

### PR DESCRIPTION
**Pull request by KAPIL9027**
fixes #19 

Hi @Abhirup-02, I have made the changes to the scrollbar as you suggested. I set the width to 11px and added a border-radius of 10px. Additionally, when I attempted to run the development server, it displayed an error message stating 'react-scripts' was not recognized. To resolve this, I installed 'react-scripts' using the command "npm install react-scripts --save".

demo video:
https://www.loom.com/share/a18bd7a8063a47b0a14eec4f5f114718

### CODE REVIEW

**Comment by zeitgeistxx** [comment]
Screenshot_20230521_090958
Everything is fine. But one thing is there. Why line no.8 is removed from frontend/package-lock.json. Fix that

**Comment by KAPIL9027** [comment]
> Screenshot_20230521_090958 Everything is fine. But one thing is there. Why line no.8 is removed from frontend/package-lock.json. Fix that

@Abhirup-02, I have fixed it. please check it, if it is fine now.

**Comment by zeitgeistxx** [comment]
Yeah it's fine, wait until the official tags arrive. Then I will merge it

**Review by zeitgeistxx — APPROVED** [review]
Thanks for your  contribution.

**Pull request merged**
