### PR TITLE
added scroll progress bar and modified scrollbar

### LINKED ISSUE #238: Adding intuitive navigation scroll in the website
## Description

**Is your feature request related to a problem? Please describe.**
no
A clear and concise description of the problem or limitation that the requested feature would address.

**Describe the solution you'd like**
A clear and concise description of the feature or enhancement you would like to see implemented.
As the user will scroll down the website, the sticky navigation condenses and becomes more minimal. Right now it just remains the same length.
**Describe alternatives you've considered**

## Additional Information

**Context**
Provide any additional context or information that helps explain the feature request.

**Potential Implementation** (optional)
If you have any ideas or suggestions on how the feature could be implemented, please share them here.

**Screenshots or Mockups** (optional)
If applicable, include any screenshots, mockups, or visual representations of the requested feature.

**Priority** (optional)
Please indicate the priority level of this feature request (e.g., High, Medium, Low).

**Additional Notes** (optional)
Add any other notes or comments about the feature request here.

### PR DESCRIPTION
**Pull request by Illaf**
I have added a horizontal progressBar with slight modifications. closes #238. Please have a look
in home.jsx

https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/114517448/27681cd7-9693-4b16-9ad8-53b75eafc3c7

In resources.jsx

https://github.com/Resourcio-Community/Resourcio_Community-Website/assets/114517448/ec8c19ca-8e49-4db9-9f91-2a9316b6d63f

The solution is slightly different from what was mentioned in the issue only because it looked better.
Also I have modified the scrollbar
Hope you'll like it!
Please tell if any further changes are required

### CODE REVIEW

**Comment by Illaf** [comment]
@Abhirup-02 Please check this pull request

**Comment by zeitgeistxx** [comment]
hey @Illaf it looks nice. But make its width less, it feels too much catchy to eye and keep the color as it was.

If possible in Home page, place scroll under the navbar. And make sure in mobile navbar toggle it doesn't mess up anything.

**Comment by Illaf** [comment]
@Abhirup-02 Okay👍

**Comment by Illaf** [comment]
@Abhirup-02 I have reduced the width of the scrollbar and optimized it in mobile mode as well. Also I tried to put it below navbar but it is not visible there perhaps due to transparent nature of navbar

**Review by zeitgeistxx — APPROVED** [review]

**Comment by zeitgeistxx** [comment]
have you turned on branch protection rule @Illaf.......i can't commit to the PR branches for some reason

**Comment by Illaf** [comment]
@Abhirup-02 no .I have only done changes manually in pull request on github itself and tested it locally. If the issue persists then i will push it from local

**Comment by zeitgeistxx** [comment]
Yeah do it please

**Pull request closed without merging**
